version: '3'
services: 
  node:
    build: ./docker/node
    container_name: server_node
    ports: 
      - "3000:3000"
    expose: 
      - 3000
    volumes:
      - ./app:/application
    command: sh
    tty: true